[build]
  publish = "dist"
  command = "npm run build:web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


<<<<<<< HEAD



=======
>>>>>>> parent of 09e167b (Add blank lines to multiple files for improved readability)
